### ISSUE TITLE
512MB RAM is not enough sometimes

### ISSUE THREAD

**Issue by sadgb** [chainpoint/chainpoint-gateway#1]
chainpoint-node_1  | 2017-09-22T09:05:15.734354696Z Initial public key import completed.
chainpoint-node_1  | 2017-09-22T09:05:15.741941682Z Node syncing local calendar with Core...
chainpoint-node_1  | 2017-09-22T09:05:15.742545983Z Validating Node Calendar blocks...
chainpoint-node_1  | 2017-09-22T09:05:19.294349552Z Validated Node Calendar blocks 0 to 62799
chainpoint-node_1  | 2017-09-22T09:05:19.303854532Z Retrieving Node Calendar most recent block info
chainpoint-node_1  | 2017-09-22T09:05:19.314015182Z Node Calendar height = 62799
chainpoint-node_1  | 2017-09-22T09:05:19.419434085Z Blockrange 628 not ready yet
chainpoint-node_1  | 2017-09-22T09:05:19.422414840Z Node startup completed successfully!
chainpoint-node_1  | 2017-09-22T09:05:20.214845195Z Core audit challenge solution calculated - ba7750604ea4742e36e0c32322dd2ea3d12dfebd9c84ba04b427925d19e67d8a
chainpoint-node_1  | 2017-09-22T09:05:37.348088924Z Killed
chainpoint-node_1  | 2017-09-22T09:05:37.358459990Z error Command failed with exit code 137.

**Comment by sadgb** [comment]
~/chainpoint-node# make down
docker-compose down
Stopping chainpointnode_chainpoint-node_1 ... done
Stopping chainpointnode_postgres_1        ... done
Stopping chainpointnode_redis_1           ... done
Removing chainpointnode_postgres_1 ... done
Removing chainpointnode_redis_1    ... done
Removing network chainpointnode_chainpoint-node
ERROR: network chainpointnode_chainpoint-node id 3b536d8b2ee6fc24deaca0d1b17fbe61e981c447c4952ff3bfcb32a36d5b8275 has active endpoints
Makefile:24: recipe for target 'down' failed
make: *** [down] Error 1

**Comment by sadgb** [comment]
After numerious reboots
chainpoint-node_1  | 2017-09-22T09:40:37.153899496Z Node startup completed successfully!
chainpoint-node_1  | 2017-09-22T09:40:37.842845328Z buffer.js:34
chainpoint-node_1  | 2017-09-22T09:40:37.845019082Z     super(arg1, arg2, arg3);
chainpoint-node_1  | 2017-09-22T09:40:37.845032295Z     ^
chainpoint-node_1  | 2017-09-22T09:40:37.845037562Z 
chainpoint-node_1  | 2017-09-22T09:40:37.845042536Z RangeError: Array buffer allocation failed
chainpoint-node_1  | 2017-09-22T09:40:37.845047559Z     at new ArrayBuffer (<anonymous>)
chainpoint-node_1  | 2017-09-22T09:40:37.845208360Z     at Buffer.Uint8Array (native)
chainpoint-node_1  | 2017-09-22T09:40:37.845215562Z     at FastBuffer (buffer.js:34:5)
chainpoint-node_1  | 2017-09-22T09:40:37.845220457Z     at Function.Buffer.alloc (buffer.js:201:10)
chainpoint-node_1  | 2017-09-22T09:40:37.845225270Z     at new Buffer (buffer.js:129:19)
chainpoint-node_1  | 2017-09-22T09:40:37.845230194Z     at module.exports.Reader.addChunk (/home/node/app/node_modules/packet-reader/index.js:35:21)
chainpoint-node_1  | 2017-09-22T09:40:37.845235632Z     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:126:18)
chainpoint-node_1  | 2017-09-22T09:40:37.845240949Z     at emitOne (events.js:115:13)
chainpoint-node_1  | 2017-09-22T09:40:37.845245756Z     at Socket.emit (events.js:210:7)
chainpoint-node_1  | 2017-09-22T09:40:37.845275789Z     at addChunk (_stream_readable.js:252:12)
chainpoint-node_1  | 2017-09-22T09:40:37.845282652Z     at readableAddChunk (_stream_readable.js:239:11)
chainpoint-node_1  | 2017-09-22T09:40:37.845287354Z     at Socket.Readable.push (_stream_readable.js:197:10)
chainpoint-node_1  | 2017-09-22T09:40:37.845291880Z     at TCP.onread (net.js:588:20)
chainpoint-node_1  | 2017-09-22T09:40:38.188278867Z error Command failed with exit code 1.

**Comment by grempe** [comment]
We agree. We've changed the official recommendation to 1GB of RAM. Please file future issues on the https://github.com/chainpoint/chainpoint-node repository. Thx!
