### ISSUE TITLE
Start tagging releases

### ISSUE THREAD

**Issue by filoozom** [chainpoint/chainpoint-gateway#18]
Hey, I just noticed that you're not currently tagging releases. I was trying to debug a specific Chainpoint node version but it's a lot harder to find the code without tags.

**Comment by grempe** [comment]
The git SHA1 of the commit in `chainpoint-node-src` Is carried over to `chainpoint-node` in it's `docker-compose.yaml` file. Public releases only emerge from `chainpoint-node` repo and are tagged there as commits+tags on master branch.
