### ISSUE TITLE
How to create a node?

### ISSUE THREAD

**Issue by Chiqui1234ok** [chainpoint/chainpoint-gateway#49]
Hi! I've been following this tutorial: https://www.reddit.com/r/tierion/comments/70lv6f/nontechnical_guide_to_set_up_tierion_node/

The server's IP are set on *LND_PUBLIC_IP* & *CHAINPOINT_NODE_PUBLIC_URI*, inside *.env* file. When I run the command **make up** is all OK (despite some warnings saying "incorrect peer dependecy), however **make ps** doesn't work because says doesn't have a "target".

Whaaat? So, I'm stuck with this tutorial. I have read another tutorials but the auto-wizard (bash script) doesn't exist anymore, so I can't go on.

Any help?  Thanks.
I have 5000 TNT ready for this node! <3

**Comment by Chiqui1234ok** [comment]
Anyone? :/

**Comment by jacohend** [comment]
@Chiqui1234 chainpoint-node is now deprecated, and no longer uses the Tierion Network Token. 

For more info, please see our [announcement](https://medium.com/tierion/tierion-sec-settlement-waiver-e3f91ab591bf).

**Comment by Chiqui1234** [comment]
> 
> 
> @Chiqui1234 chainpoint-node is now deprecated, and no longer uses the Tierion Network Token.
> 
> For more info, please see our [announcement](https://medium.com/tierion/tierion-sec-settlement-waiver-e3f91ab591bf).

Hi @jacohend , I'm a little bit confused. I can't create a TNT node for staking anymore? Or this is achivable thanks to [Chainpoint-Core](https://github.com/chainpoint/chainpoint-core)?

Thanks in advance :)
