### ISSUE TITLE
Ignoring unsupported options: build, restart - is this a problem ?

### ISSUE THREAD

**Issue by jo2h2** [chainpoint/chainpoint-gateway#50]
Hello everyone,

maybe someone can give me a good hint as I am lost - I followed https://github.com/chainpoint/chainpoint-gateway to setup a chainpoint gateway and I was successful up to the point where I need to run "make deploy":

```
chainpoint@chainpoint-gateway:~/chainpoint-gateway$ make deploy
set -a && source .env && set +a && export USERID=1001 && export GROUPID=1001 && docker stack deploy -c swarm-compose.yaml chainpoint-gateway
Ignoring unsupported options: build, restart

Creating network chainpoint-gateway_chainpoint-gateway
Creating service chainpoint-gateway_lnd
Creating service chainpoint-gateway_ln-accounting
Creating service chainpoint-gateway_chainpoint-gateway
```

Here I am confused about "Ignoring unsupported options: build, restart" - is this a problem for me running the gateway ? And if so, how can I fix this ?

Thanks a lot !

Best wishes,
Jo ...

**Comment by jacohend** [comment]
This is not a problem
